# 1. ndim 이해하기

In [1]:
import numpy as np

In [2]:
x = np.array(5)
x.ndim

0

In [3]:
x = np.array([32, 5, 3, 43, 27])
x.ndim

1

In [4]:
x = np.array([[32, 5, 3, 43, 27], [28, 76, 0, 33, 46], [11, 9, 24, 83, 47]])

x = np.array([[32, 5, 3, 43, 27],
              [28, 76, 0, 33, 46],
              [11, 9, 24, 83, 47]])

x.ndim

2

In [5]:
x = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
              [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])

x = np.array([[[1, 2, 3, 4, 5], 
               [6, 7, 8, 9, 10]],
              [[11, 12, 13, 14, 15], 
               [16, 17, 18, 19, 20]],
              [[21, 22, 23, 24, 25], 
               [26, 27, 28, 29, 30]]])
x.ndim

3

In [6]:
x.shape

(3, 2, 5)

In [7]:
np.max(x, axis=0)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
np.argmax(x, axis=0)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int64)

# 2. shape 이해하기

In [9]:
a = np.array([[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]])
a.shape

(3, 5)

In [10]:
a = np.array([[[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]], 
              [[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]]])
a.shape

(2, 3, 5)

### - np.reshape

In [11]:
a.reshape((6,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [12]:
a.reshape((-1,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
a.reshape((-1,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [14]:
a.reshape((1,1,2,3,5))

array([[[[[5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5]],

         [[5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5]]]]])

### - np.ravel

In [15]:
np.ravel(a)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

### - np.squeeze

In [16]:
np.squeeze([[[1]],[[2]],[[3]]])

array([1, 2, 3])

### - np.expand_dims

In [17]:
np.expand_dims([[1], [2], [3]], axis=0)

array([[[1],
        [2],
        [3]]])

### - np.stack

In [18]:
x = [1,2]
y = [3,4]
z = [5,6]

np.stack([x,y, z], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.stack([x,y,z], axis=1)

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
np.stack([x,y,z])

array([[1, 2],
       [3, 4],
       [5, 6]])

# 3. 브로드 캐스팅(broad casting)

In [21]:
x = np.array([1,2])
y = np.array(3)

print(x + y)

[4 5]


In [22]:
x = np.array([[1,2]])
y = np.array([3,4])

print(x + y)

[[4 6]]


In [23]:
x = np.array([[1,2], [5,6]])
y = np.array([3,4])

print(x + y)

[[ 4  6]
 [ 8 10]]


In [24]:
x = np.array([[1,2]])
y = np.array([[3],[4]])

print(x + y)

[[4 5]
 [5 6]]


# 4. axis 이해하기

In [25]:
x = [[1, 2],
     [3, 4]]

### - np.mean

In [26]:
print(np.mean(x, axis=0))

[2. 3.]


In [27]:
print(np.mean(x, axis=1))

[1.5 3.5]


In [28]:
print(np.mean(x, axis=-1))

[1.5 3.5]


In [29]:
print(np.mean(x))

2.5


### - np.sum

In [30]:
print(np.sum(x, axis=0))

[4 6]


In [31]:
print(np.sum(x, axis=1))

[3 7]


In [32]:
print(np.sum(x, axis=-1))

[3 7]


In [33]:
print(np.sum(x))

10


### - np.argmax

In [34]:
x = [[0, 1, 2],
     [3, 1, 0]]

In [35]:
print(np.argmax(x, axis=0))

[1 0 0]


In [36]:
print(np.argmax(x, axis=1))

[2 0]


In [37]:
print(np.argmax(x, axis=-1))

[2 0]


In [38]:
print(np.argmax(x))

3


# 5. 점곱(dot product)

In [39]:
a = np.array([1,2])
b = np.array([10,20])

print(np.dot(a,b))

50


In [40]:
print(a@b)

50


In [41]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,9,11],
             [8,10,12]])

print(np.dot(a,b))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
c = b.T
print(c)

print()

print(np.dot(a,c))

### - 퍼셉트론 기본 연산으로의 표현

In [ ]:
keras.layers.Dense(512, activation='relu')

In [ ]:
relu(dot(W, input) + b)

In [ ]:
x = dot(W, input) + b
max(x, 0)